#pragma once

#include "moe/core/config.hpp"
#include "moe/core/error.hpp"
#include "moe/core/weight_source.hpp"

namespace ascend_moe::mock {

// Mock DMA checks address intervals and never consumes tensor bytes. Avoid
// writing generated bytes to symbolic host slots (which have no backing RAM).
class SymbolicWeightSource : public WeightByteSource {
 public:
  SymbolicWeightSource(const ExpertSlotLayout& layout, int64_t layers, int64_t experts)
      : layers_(layers), experts_(experts) { layout_ = layout; }
  const char* source_name() const override { return "synthetic-symbolic"; }
  bool Contains(int32_t layer, int32_t expert) const override {
    return layer >= 0 && layer < layers_ && expert >= 0 && expert < experts_;
  }
  void ReadExpertSlotRange(uint8_t*, size_t capacity, size_t offset, size_t count,
                           int32_t layer, int32_t expert) override {
    RefuseIfClosed("symbolic expert read");
    DSV4_REQUIRE(Contains(layer, expert), "symbolic expert outside coverage");
    DSV4_REQUIRE(offset <= layout_.slot_num_bytes() && count <= layout_.slot_num_bytes() - offset &&
                     count <= capacity, "symbolic expert read outside slot");
  }
  bool HasNamed(const std::string&) const override { return true; }
  size_t NamedByteSize(const std::string&) const override { return 0; }
  void ReadNamed(const std::string&, uint8_t*, size_t capacity, size_t, size_t count) override {
    RefuseIfClosed("symbolic named read");
    DSV4_REQUIRE(count <= capacity, "symbolic named read outside destination");
  }
  void Close() override { closed_ = true; }
 private:
  int64_t layers_;
  int64_t experts_;
};

// Synthetic oracle, only installed by a mock build. These outputs are not
// model predictions: they drive routing and greedy readback contract checks.
inline void SeedSyntheticReadback(void* destination, size_t count) {
  if (count == sizeof(int32_t) * static_cast<size_t>(kNumExpertsPerTok)) {
    auto* ids = static_cast<int32_t*>(destination);
    for (int64_t i = 0; i < kNumExpertsPerTok; ++i) ids[i] = static_cast<int32_t>(i);
  } else if (count == sizeof(int64_t)) {
    *static_cast<int64_t*>(destination) = 0;
  }
}
}  // namespace ascend_moe::mock
